# Generated by Django 5.2.7 on 2025-10-10 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.CharField(choices=[('direct', 'Direct Therapy'), ('indirect', 'Indirect Therapy'), ('supervision', 'Supervision'), ('documentation', 'Documentation'), ('travel', 'Travel Time'), ('training', 'Training'), ('meeting', 'Meeting')], default='direct', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_time_trackers', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_trackers', to='session.session')),
            ],
            options={
                'verbose_name': 'Time Tracker Entry',
                'verbose_name_plural': 'Time Tracker Entries',
                'ordering': ['-start_time'],
            },
        ),
    ]
