# Generated by Django 5.2.7 on 2025-10-10 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_timetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontimer',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
