# Generated by Django 5.2.7 on 2025-10-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_business_city_customuser_business_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_zip_code',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='business_city',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='business_country',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='business_state',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='business_zip_code',
        ),
    ]
