# Generated by Django 5.2.6 on 2025-09-25 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_type',
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role__in': [3, 2]}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
