# Generated by Django 5.2.6 on 2025-09-26 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_session_recurring_remove_session_session_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Clients/Parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['RBT', 'BCBA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
